# name : Enterprise DevSecOps Lab #display name 

# on: #trigger
#   workflow_dispatch:
#     branches:
#       - main

# jobs: #every pipeline has jobs and each job has steps
#  #job 1
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Say Hello
#         run: |
#           echo "Hello, Enterprise DevSecOps Lab!"
#           echo "Wellcome started Successfully!"

#       - name: Display GitHub Content
#         run: |
#           echo "Repository Content: ${{ github.repository }}"
#           echo "Repository Owner: ${{ github.repository_owner }}"     
#           echo "Branch: ${{ github.ref_name }}"
#           echo "Actor: ${{ github.actor }}"
#           echo "Workflow: ${{ github.workflow }}"
#           echo "Run Number: ${{ github.run_number }}"
#           echo "Commit SHA: ${{ github.sha }}"
        
#       - name: Repository Name
#         run: |
#           REPO_NAME=$(basename "${{ github.repository }}")
#           echo "Repository Name: $REPO_NAME"


#       - name: Display System Info
#         run: |
#           echo "System Information:"
#           uname -a
#           echo "CPU Information:"
#           lscpu
#           echo "Memory Information:"
#           free -h
#           echo "Disk Usage:"
#           df -h
#           echo "Current Date:"
#           date