name : Enterprise DevSecOps Lab #display name 

on: #trifgger
  push:
    branches:
      - main
  # pull_request:
  #   branches:
  #     - main

jobs: #every pipeline has jobs and each job has steps
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: |
          echo "Hello, Enterprise DevSecOps Lab!"
          echo "Wellcome started Successfully!"

job:
  system-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display System Info
        run: |
          echo "System Information:"
          uname -a
          echo "CPU Information:"
          lscpu
          echo "Memory Information:"
          free -h
          echo "Disk Usage:"
          df -h
          echo "date and Time:"
          date && time